### ISSUE TITLE
RFC: Add a one-click-try-out button

### ISSUE THREAD

**Issue by BracketJohn** [sidebase/sidebase#10]
### Describe the feature

something like:
<img width="577" alt="image" src="https://user-images.githubusercontent.com/25911230/188427166-2ebb2003-6994-4f81-824f-761d2a280937.png">

we can use stackblitz.

**Comment by j-wil** [comment]
I like the work going on here!

I will say you already have a one-click try-out button.


![Screenshot 2022-12-18 112140](https://user-images.githubusercontent.com/7523651/208311065-5deef5ab-1b1c-4998-85ee-675dc4a8bd17.png)

**Comment by BracketJohn** [comment]
Thanks @j-wil -> awesome point ❤️ 

Something else to add: With `npm create sidebase@latest` it has already become easier to try `sidebase` out locally (: But ofc. the one-click-tryout experience is still better / different (:

**Comment by BracketJohn** [comment]
closing this for now, as I think the need is not super big atm + we already have a good option (see @j-wil 's comment)
