### ISSUE TITLE
Add more info about the company to the readme

### ISSUE THREAD

**Issue by valiafetisov** [sidebase/sidebase#11]
### Describe the feature

@BracketJohn aren't we hiring full-stack developers at the moment? I see that a lot of stargazers fits our profile, so we might add a section `we're hiring`. We might also add a section about the company and add direct contact info to get in touch if people need help to develop something.

### Additional information

Suggested structure would be:

```
## Sidebase is baked by Sidestream

[Sidestream](https://sidestream.tech/) is a [remote-first] software agency based in Germany. Other information about the company...

- We can develop a project for you, [get in touch](the-email)
- We're hiring full stack developers, [apply here](the-link)
```

**Comment by danielkremerov** [comment]
@chanpignon this is for you

**Comment by BracketJohn** [comment]
I think for now this is not needed.

We have the offical https://sidebase.io page to represent.

We also have https://github.com/sidebase as a general overview. Let's re-open this later or open a new, more specific issue as soon as we want to act here.
