### ISSUE TITLE
Adding HeadlessUI

### ISSUE THREAD

**Issue by zoey-kaiser** [sidebase/sidebase#12]
### Describe the feature

HeadlessUI is a unstyled utility library made by the creators of TailwindCSS.
It extends TailwindCSS to allow one to add more complex animations and components. I believe that in some instances it is super helpful, as it allows you to create completely customised drop-downs, lists and modals.

Link: https://headlessui.com/

**Comment by BracketJohn** [comment]
Hm, should we close this issue in favor of the comparison in #2?

Also, would we still use this is we switch to quasar / primevue?

**Comment by zoey-kaiser** [comment]
I was thinking of adding it in there as well, however Headless UI is not comparable IMO, as it is less of a UI library and more just some unstylish boiler functionality for complex components.

I personally really like their Animation component and feel like it is often missing in other libraries.

**Comment by BracketJohn** [comment]
we've settled with naive UI for now. This issue will be closed via #80
