### ISSUE TITLE
RFC: Collect possible nuxt-module ideas

### ISSUE THREAD

**Issue by BracketJohn** [sidebase/sidebase#17]
### Describe the feature

Collect possible ideas for useful nuxt-modules we can pull out of sidebase for easier development + versioning + distribution.

Modules docs: https://v3.nuxtjs.org/guide/going-further/modules

### Additional information

Ideas so far:
- [ ] nuxt-typeorm: Easy typeorm integration for nuxt, could even allow client-side usage of typeorm-objects, e.g., converting it to API-calls if on the client side
- [ ] nuxt-secrets: Integration for `chamber` to use `AWS SSM` easily from app
- [ ] nuxt-pdf
- [ ] nuxt-swagger
- [x] nuxt-server-parse: Make a module out of https://github.com/sidestream-tech/sidebase/blob/main/app/server/helpers.ts
  - library: https://github.com/sidebase/nuxt-parse
  - comment: with the current nuxt 3 state probably better to use `zod` or `tRPC`, e.g., via `npm create sidebase@latest`
- [x] nuxt-prisma
  - layer: https://github.com/sidebase/nuxt-prisma

**Comment by valiafetisov** [comment]
- I also vote for isolating `zod`-related functionality
- It will be very helpful to have auth figured out, since almost every api-enabled app needs it
- deployment-related functionality (eg single button deployment)

**Comment by Atinux** [comment]
Have you seen https://github.com/wobsoriano/h3-zod ?

**Comment by BracketJohn** [comment]
Yes! But, it uses an old h3 version so some of the methods are deprecated + some utilty methods are missing that would play really nicely with transform of `useFetch`!

See our take on it here: https://www.npmjs.com/package/@sidestream-tech/nuxt-sidebase-parse

screencap of one utility for tldr:
<img width="725" alt="image" src="https://user-images.githubusercontent.com/25911230/188712599-dd48632c-2f98-4af2-92a3-f3fc70b73b3f.png">

**Comment by wobsoriano** [comment]
@BracketJohn it's using the latest h3 now. Thanks for the heads up!

**Comment by BracketJohn** [comment]
Sure thing ❤️ Awesome that you've already integrated it into h3-zod!

**Comment by BracketJohn** [comment]
Thanks everybody for comments + participation. Closing this issue now as it has no clear goal and acts only as a "notepad". Let's open individual issues if someone has a module request or discuss further on our discord: https://discord.gg/9MUHR8WT9B
