### ISSUE TITLE
Sidebase Youtube Tutorial

### ISSUE THREAD

**Issue by DaeunYoon** [sidebase/sidebase#26]
### Describe the feature

When I was searching for good learning methods & tutorials for vue/nuxt it was comparably more difficult than other frameworks' tutorials, although these days there are more and more good tutorials, it is still difficult to find up-to-date tutorials.

So, I suggest making Nuxt tutorials with Sidebase (which has up-to-date nuxt & related libraries)

This could help not only people who just start to use Sidebase scaffold but also people who start to learn Nuxt/Vue but don't know where to start. 

### Initial Tutorial Idea
 - Kick-off nuxt project
 - How to use API in Nuxt
 - How to use Nuxt3 built-in composables

**Comment by BracketJohn** [comment]
Love the idea!

Let's expand on https://www.youtube.com/watch?v=Wu9LQ7L5BcU&feature=emb_title then with this (:

**Comment by BracketJohn** [comment]
Closing this now, let's re-open this here or elsewhere once we want to push it further / more requests for this come in.

Thank you so much for the suggestion though @DaeunYoon (:
