### ISSUE TITLE
Investigate the usage of different Vue3 UI Component frameworks

### ISSUE THREAD

**Issue by zoey-kaiser** [sidebase/sidebase#27]
**Goal**

In #2 we made a list of multiple Vue component frameworks we might want to add support for. The next step is to narrow down the selection and create separate branches running on these frameworks. This can be used to test their integration into our scaffold, their features and ease of use.

**Context**
We currently use AntDesign 3. As we also have a lot of experience with this framework, it will be left out of the investigation and be seen as a given, that we always provide at least one version with AntDesign. The frameworks I will be creating branches for in the future will be:

- PrimeVue
- Naive UI (thanks to @ManUtopiK 😊)
- Element UI

I can imagine checking more in the future, however to keep the scope of this issue down I have narrowed it to these three I plan to implement in the first wave.

**Comment by BracketJohn** [comment]
Naive UI it is!

Will be added + closed via #80
