### ISSUE TITLE
Add Nuxt Types Router

### ISSUE THREAD

**Issue by zoey-kaiser** [sidebase/sidebase#41]
### Describe the feature

Add a package, that adds typescript support for routes. 
https://github.com/victorgarciaesgi/nuxt-typed-router

Demo:
![image](https://raw.githubusercontent.com/victorgarciaesgi/nuxt-typed-router/master/medias/in-action.gif)

**Comment by BracketJohn** [comment]
I'm on my phine right now so I can't verify the following claim, but I _think_ that this is already the default for nuxt 3. Am I wrong?

**Comment by BracketJohn** [comment]
closing -> this is part of core nuxt 3 already AFAIK (:
