### ISSUE TITLE
TailwindCSS only correct loads on Hard Refresh when starting dev server

### ISSUE THREAD

**Issue by zoey-kaiser** [sidebase/sidebase#48]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.10`
- Nitro Version:    `0.5.3`
- Package Manager:  `npm@8.5.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

When running a `sidebase` app in the newest version, the Tailwind styles only correctly load when hard refreshing `CTL` + `F5`. When reloading normally it looks like this:

https://user-images.githubusercontent.com/30908158/191063801-56b18d9d-8130-4f61-b012-c3dace1dda50.mov

**Comment by BracketJohn** [comment]
Cannot replicate it in my env in Firefox - can you look into your browser console / network tab and see if there's any hints there?

**Comment by zoey-kaiser** [comment]
I found the following error in my console:

```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.
```

**Comment by BracketJohn** [comment]
Interesting - can you look into it for your own setup then?
