### ISSUE TITLE
Removing package-lock.json and make repo independent of development

### ISSUE THREAD

**Issue by ineshbose** [sidebase/sidebase#53]
A starter template should ideally not include a lock-file to allow usage of other dependency managers (also instructed in https://github.com/nuxt/starter). Removing that from the repository could get difficult for development, so a branching & CI may need to be setup (happy to look into myself & create a PR when I get time).

_Issue started from https://github.com/sidestream-tech/sidebase/issues/13#issuecomment-1258137528_

**Comment by ineshbose** [comment]
Hi @zoey-kaiser,

I'm just working on this and I believe I have something setup, but it would require a `dev` branch as mentioned if you create one for this repository so that I can create a PR and I'll add additional info on the request. 🙂

**Comment by zoey-kaiser** [comment]
> I'm just working on this and I believe I have something setup, but it would require a `dev` branch as mentioned if you create one for this repository so that I can create a PR and I'll add additional info on the request. 🙂

Thank you for looking into the matter! I sadly do not have the permissions to give you access to create a new branch on the repo. Therefore I will pass this request on to @BracketJohn!

**Comment by BracketJohn** [comment]
Like the idea, had a look, let's discuss in #57 💯

**Comment by BracketJohn** [comment]
This may be closed via #80

**Comment by BracketJohn** [comment]
This issue was basedx on #57 as a sub-part of it that we can resolve early. With `create-sidebase` CLI now exisitng, the overarching issue was resolved as `create-sidebase` is already _fully_ development independent.

Use it like this:
```sh
npm create sidebase@latest
```

Works with any other package manager as well (: 

Closing this now.
