### ISSUE TITLE
Investigate CLI options

### ISSUE THREAD

**Issue by zoey-kaiser** [sidebase/sidebase#59]
I was looking at other `create_blank_app` cli tools and the one that seemed the most promising is [`create_nuxt_app`](https://github.com/nuxt/create-nuxt-app).

They have the following structure:

## SAO
They use a tool called [SAO](https://sao.vercel.app/) which is a scaffolding tool. It lets you define specific [generators](https://sao.vercel.app/guide/creating-generators.html), that can combine different parts of a scaffold together. You can then pass options to the generators to scaffold a custom project based on the user input.

I would recommend that we create seperate branches for each `lib` (addon that can be changed eg. CSS framework or backend). Once we have the seperate branches we can compare them with main and see which files will need to be updated.

This is their SAO generator file. It defines where to get the different parts of the project that can then be installed: https://github.com/nuxt/create-nuxt-app/blob/master/packages/create-nuxt-app/lib/saofile.js

Inside the generator file you can define actions to build the starter:

### Actions

Adds files to the template
```ts
if (this.answers.ui !== 'none') {
  actions.push({
    type: 'add',
    files: '**',
    templateDir: join(frameworksDir, this.answers.ui)
  })
}
```

Move files from one place to another
```ts
actions.push({
  type: 'move',
  patterns: {
    gitignore: '.gitignore',
    '_package.json': 'package.json',
  }
})
```

Modify a file
```ts
actions.push({
  type: 'modify',
  files: 'package.json',
  handler (data) {
    return { ...data, ...pkg.load(generator) }
  }
})
```

Remove a file
```ts
actions.push({
  type: 'remove',
  files: 'package.js'
})
```

## Templates
In a [separate folder](https://github.com/nuxt/create-nuxt-app/tree/master/packages/cna-template/template/frameworks) they have all the required files to add a specific technology or framework. While their system is a bit more simple then ours (no backend), I think we can split specific parts of our starter into smaller segments.

Lets take the backend as an example:
We could move all the files we need for the backend to work in another folder. In our case these files would be:

- `package.json` with only the extra packages and scripts needed to run the backend
- `/server`
- `/tests/server`

When the developers selected `with-backend` these files will be copied over. The templates folder is a seperate npm package, which is installed inside the CLI package. Through this the files can be accessed. 

## Prompts
They have one file in which all their questions are defined: https://github.com/nuxt/create-nuxt-app/blob/master/packages/create-nuxt-app/lib/prompts.js
These questions are asked and the answers are collected. SAO comes with a custom prompt system that we can use!

## Conclusion
This option for the CLI will require a rewrite of the sidebase template. We will have to decide if we want to keep a demo version of sidebase in this repo, or if we create a new repo (or use sidebase-libs), however I believe this is the best option we can take to ensure we can continue to expand sidebase!

**Comment by zoey-kaiser** [comment]
I would also recommend we use [CAC](https://github.com/cacjs/cac) to manage our CLI, as it allows us to easily add flags and more commands in the future.

**Comment by BracketJohn** [comment]
Thanks!

Other options I found are: `plop`, `hygen`, `slush`.

Can you also look into those and see how they compare to sao / yeoman? Maybe one of them has a fresher approach -> SAO is deprecated by the maintainer.

**Comment by zoey-kaiser** [comment]
## Plop
Plop is based on [`handlebars`](https://github.com/handlebars-lang/handlebars.js), which means that all files that may be copied over will have to be written in the `.hbs` type. I am not sure how hard it will be to adjust our linting and tests accordingly. @BracketJohn, do you have any infos on this?

Other then this little issue, I like their syntax a lot. From all the packages it looks the easiest to use. It also uses [`inquiry.js`](https://github.com/SBoudrias/Inquirer.js/) as their prompt manager, which is a very advanced and versatile package that allows you to ask users complex questions.  

An example for a template file can be found here: https://github.com/ru03/plopjs-example/tree/master/plop-templates
An example for the main "build" files can be found here: https://github.com/ru03/plopjs-example/blob/master/plops/redux.js

They structure their templates folder with separate folders for every question option. These parts are then imported and used accordingly. 

What I really like about this package:
- Easy to learn syntax
- Little setup required
- Many prompt options
- Well integrated bridge between 2 stable, well maintained packages (handlebars and inquiry.js)

What we need to check:
- Can be use `.hbs` files or will that destroy our options for linting/testing

## Hygen
Hygen uses a similar approach to Yeoman, in the sense that it uses its own template language to allow us to scaffold a project. There is an example at [`hygen-CRA`](https://github.com/jondot/hygen-CRA), however a lot of points I mentioned with Yeoman still apply. I belive that this kind of templating system becomes hard to maintain over a longer period of time. See an example of the template file here: https://github.com/jondot/hygen-CRA/blob/master/_templates/component/new/index.js.t

However, I would say, that if we do decide to use a scaffolding system that uses this apporch I would choose hygen over Yeoman. 
Reasons:
- Less boilerplate and easier to setup
- Easier syntax and less work to boilerplate
See more reasons here: http://www.hygen.io/docs/faq#why-should-i-use-hygen

## Slush
What I noticed immediately was that the last update was done in 2015. For me this is a pretty big red flag, as it seems that this package gets little support now adays. When going through their issues I also saw reports of [security vulnerabilities ](https://github.com/slushjs/slush/issues/65). These issues are also not addressed by the maintainers. 

Because of these reasons I would recommend we do not go with slush!

**Comment by BracketJohn** [comment]
So as discussed orally: `plop` seems to be the most maintained + allows us to also change code _inside_ the files we copy easily if we want to  via variables. One last thing to checkout before deciding: Do we _have_ to use `.hbs` files always or do we have the option to put in vanillas `ts` and `js` files if we do not want variable-interpolation?

**Comment by zoey-kaiser** [comment]
> So as discussed orally: `plop` seems to be the most maintained + allows us to also change code _inside_ the files we copy easily if we want to via variables. One last thing to checkout before deciding: Do we _have_ to use `.hbs` files always or do we have the option to put in vanillas `ts` and `js` files if we do not want variable-interpolation?

In this example here, they show how they use a `.txt` file as a template file. Therefore I assume other files should work as well!

https://github.com/plopjs/plop#using-a-dynamic-actions-array

**Comment by zoey-kaiser** [comment]
## My experiences with working with Plop

- Even if the file is not a `.hbs` files handlebars will still parse it. This means that any Vue components that use `{{ SOME_THING }}` will need to be modified to the following:

```
{{{{raw}}}}
  <a>{{ statusCheck.nuxtAppVersion.toString() }}</a>
{{{{/raw}}}}
```

This escapes the handlebar rendering. https://handlebarsjs.com/guide/expressions.html#whitespace-control

**Comment by zoey-kaiser** [comment]
> Plop

After working with plop to bring a V1 out I can document the following experiences I had:

- the default `plop` package, requires that we build our cli on top of their cli. Meaning that in the end we run a script on top of the plop script and just pass our `plopfile.js` to it. See branch https://github.com/sidebase/create-nuxt3-app/tree/add-plop-cli for current implementation. This limits us in the following ways:
  - Our design will always look like the plop CLI
  - If we ever need to add custom features, we will be limited in that sense
  - compiling to TS is really hard and trying to combine it into our cli is pretty exhausting (if we ever want to add more features)
- What I do like about it:
  - It lets us define multiple generators, allowing us to later on add features such as a component generator (where component file, story and test are pre-generated to allow for a quicker workflow).
  - Adding new templates is not that hard

Plop has an extra package called `plop-node`, which is just the core functions from plop. It is without built in prompts, but therefore allows to be complied and run independently. `node-plop` takes a `plopfile` and then runs it. However you need to pass all the options to it, for it to do it correctly. I tried working with this, however there is very little documentation on how to use it correctly, especially with typescript, which has slowed down my progress. See https://github.com/sidebase/create-nuxt3-app/tree/add-cli-v1 for current implementation. And see https://github.com/plopjs/plop/tree/main/packages/node-plop for entire existing documentation on it.

The main issue I am currently facing with this implementation is how to do the file linking correctly. In order for the project to work correctly I almost need two project in one.

- The CLI we build where users get prompted
- The generator files and plopfile

I currently have these two seperated into the `src` folder (which is also compiled from ts) and the `generators` folder (which stays in JS). There is also the `templates` folder which, contains all the template files to copy over later.

Within the `src/index.ts` I call the `node-plop` function to get the plopfile and generator. 

```ts
const plop = await nodePlop(`./plopfile.js`);
```

Which already brings me to problem one. How do I correctly link this file? As it takes in a string I am not sure how it will behave once complied etc. 

Does it make sense to make two separate packages? One being the cli and the other being the generators? Then we can just import the plopfile from the other package?

The next issue I run into is the differences between commonjs and modules. 
I found while running the `node-plop` package that I needed to add `type="module"` to the `package.json` for the project to compile correctly. However, The generator files need to export a module (https://github.com/sidebase/create-nuxt3-app/blob/add-cli-v1/packages/create-nuxt3-app/generators/sidebase.js#L1). In all the examples the generators are then imported via `const generator = require('generator.js')`, which throws me new errors then! 

In the current implementation I get the following error when running:

```sh
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/zoey/Documents/Development/SideStream/sidebase/create-nuxt3-app/packages/create-nuxt3-app/generators/sidebase' imported from /Users/zoey/Documents/Development/SideStream/sidebase/create-nuxt3-app/packages/create-nuxt3-app/plopfile.js
```

> SAO

Due to the fact I was struggling with these two options, I also had a look at SAO again. The most attractive part of SAO is not the package itself, but that fact that there is `create-nuxt-app` which uses SAO and we can use their CLI as a base on which we build ours. https://github.com/nuxt/create-nuxt-app/tree/master/packages/create-nuxt-app
This will make development a lot quicker and easier, as we won't have to reinvent the wheel. However as we mentioned above we would prefer to use plop over SAO, which I why I suggest I continue looking into it for a while.
