### ISSUE TITLE
RFC: Add modules and libraries you'd like to see in `sidebase`

### ISSUE THREAD

**Issue by zoey-kaiser** [sidebase/sidebase#62]
This is a thread for interesting Vue3 packages that people have found that we may want to integrate at some point!

**Comment by zoey-kaiser** [comment]
https://whattheframework.netlify.app/

Interesting website to help people decide which framework to use

**Comment by zoey-kaiser** [comment]
https://auto-animate.formkit.com/

Easy to use animation library to rapidly display UI changes to users

**Comment by ZainW** [comment]
Vueuse is a must have in all projects! its a bunvch of useful common composables for the web (and more)
https://vueuse.org/

**Comment by BracketJohn** [comment]
Yeah, `vueuse` is awesome!

So far sidebase only includes what's needed to get started in a minimal way. If we can add a use-case in the current setup for `vueuse` already, I agree that we should go for it!

**Comment by BracketJohn** [comment]
Closing this collection issue now as it has no clear goal / deliverable. Instead, let's open individual issues / people should open an issue / discussion / talk on discord: https://discord.gg/9MUHR8WT9B to discuss 💯
