### ISSUE TITLE
Gives errors on npm install

### ISSUE THREAD

**Issue by DaeunYoon** [sidebase/sidebase#68]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `^3.0.0-rc.10`
- Nitro Version:    `-`
- Package Manager:  `npm@8.5.0`
- Builder:          `webpack`
- User Config:      `alias`, `typescript`, `build`, `modules`
- Runtime Modules:  `@nuxtjs/tailwindcss@^5.3.5`
- Build Modules:    `-`

### Reproduction

```zsh
> npx nuxi@latest init -t community/sidebase
> cd nuxt-sidebase-app
> npm i
```

### Describe the bug

`npm install` fails with the error log below.

```zsh
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm ERR! code E404
npm ERR! 404 Not Found - GET https://cdn.npmmirror.com/packages/destr/1.2.0/destr-1.2.0.tgz
npm ERR! 404 
npm ERR! 404  'destr@https://registry.npm.taobao.org/destr/-/destr-1.2.0.tgz' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/daeunyoon/.npm/_logs/2022-10-20T21_21_07_641Z-debug-0.log
```

### Additional context

-

### Logs

```shell
-
```

**Comment by zoey-kaiser** [comment]
Hi @DaeunYoon!

Is this issue still current? Have you had a chance to try it again?

```
npm ERR! 404 Not Found - GET https://cdn.npmmirror.com/packages/destr/1.2.0/destr-1.2.0.tgz
```

This looks like NPM had issue downloading a specific package. When navigating to the URL now, it downloads the ZIP of the package. Maybe npm had an issue which made it return 404 for a brief period of time!

**Comment by DaeunYoon** [comment]
This issue has been resolved! Thank you for your reply :)
