### ISSUE TITLE
Issue saving a typeorm entity

### ISSUE THREAD

**Issue by damgem** [sidebase/sidebase#72]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.10`
- Nitro Version:    `0.5.3`
- Package Manager:  `npm@8.8.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/damgem/sidebase-typeorm-test (only `app.vue` is modified - see [commit](https://github.com/damgem/sidebase-typeorm-test/commit/3e115a8961f021f602f6d913812904da810fb3aa))

### Describe the bug

Saving an example entry does not work.
I've tried the 4 following approaches with all them producing an error in the browser console.
For the first two approaches the error message is `DataSource is not set for this entity.`  and appears _on execution_ while the latter ones produce an `connection.driver.options is undefined` error _on page load_.

```ts
const exampleData = {
  description: 'blah',
  details: 'blub',
}

// Will throw `DataSource is not set for this entity.` error when executed
const example = new Example()
await example.update(exampleData) // internally calls `.save()`

// Will throw `DataSource is not set for this entity.` error when executed
await Example.save<Example>(exampleData)

// Will throw `connection.driver.options is undefined` error on page load
await AppDataSource.manager.save(Example, exampleData)

// Will throw `connection.driver.options is undefined` error on page load
const exampleRepository = AppDataSource.getRepository(Example)
await exampleRepository.save(exampleData)
```

### Additional context

I'm not sure this is a bug or rather an user error - anyways some guidance / documentation is appreciated :)

#### Warning & Error on execution for approach 1 and 2
```
[Vue warn]: Unhandled error during execution of component event handler 
  at <AButton onClick=fn<insertExample> > 
  at <App key=1 > 
  at <NuxtRoot> runtime-core.esm-bundler.js:38:16
```

```
Uncaught (in promise) Error: DataSource is not set for this entity.
    NuxtJS 2
    update Base.ts:31
    insertExample app.vue:13
    NuxtJS 4
    handleClick2 ant-design-vue_es.js:16419
    NuxtJS 49
BaseEntity.ts:115:18
    NuxtJS 5
    emit$1 self-hosted:1406
    get emit/< NuxtJS
    handleClick2 ant-design-vue_es.js:16419
    NuxtJS 48
    InterpretGeneratorResume self-hosted:1819
    AsyncFunctionNext self-hosted:807
    (Async: async)
    <anonymous> NuxtJS
```

#### Error on page load for approach 3 and 4

```
Uncaught TypeError: connection.driver.options is undefined
    NuxtJS 3
        create
        createEntityManager
        DataSource
    <anonymous> index.ts:5
EntityManagerFactory.ts:15:12
```

for context: `index.ts:5` is a reference to `server/database/index.ts` starting on line 5 with

```ts
const AppDataSource = new DataSource({
  type: 'sqlite',
  // TODO: Only synchronize in production once we're stable
  synchronize: !isProduction || true,
  logging: false,
  database: ':memory:',
  entities: [Example],
})
```

**Comment by BracketJohn** [comment]
Sorry to say: This is likely a user-error.

Looking at your code, it seems you're referencing these lines:
https://github.com/damgem/sidebase-typeorm-test/blob/3e115a8961f021f602f6d913812904da810fb3aa/app.vue#L1-L25

The `app.vue` is loaded on the client-side, so in your browser. That place does not have a connection to the database or the server, as it's the frontend, not the backend! On the backend, the data source is initialized on startup automatically, see: https://github.com/damgem/sidebase-typeorm-test/blob/3e115a8961f021f602f6d913812904da810fb3aa/server/plugins/initTypeOrmOnServerStartup.ts

Code like this _will (hopefully)_ work right away on the server side, see the exmaples in the `api/` folder.

Closing this issue now as it likely comes from a misunderstanding, feel free to re-comment here / open a new one if something else arises.
